baseURL       = "https://www.vivieng.com/"
languageCode  = "fr"
title         = "Développeur front et intégrateur web"
summaryLength = "10"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Réalisations"
    url     = "projects"
    weight  = 2
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 3

# Site Params
[params]
  logo = "/images/vivieng-logo.png"
  alt = "VivienG logo"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Développeur web pouvant créer votre site internet et vous apporter de la visibilité sur google."
  author = "VivienG"
  keywords = "vivieng, création site internet, front end, vuejs, Vue3, react, développeur web"
  metaimage = "/images/vivieng-meta-image.jpg"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  

  # Banner Section
  [params.banner]
    enable                = true
    image_small           = "/images/vivieng-hero-small.jpg"
    image_big             = "/images/vivieng-hero-big.png"
    alt                   = "VivienG"
    heading               = "VIVIENG"
    tagline               = "Développeur Web front-end"
    primary_button        = "voir mon cv"
    primary_button_url    = "/images/CV_GRENIER_VIVIEN_front.pdf"
    secondary_button      = ""
    secondary_button_url  = ""

  [params.portfolio]
    enable              = true
    title               = "Réalisations"
    subtitle            = "Portfolio"
    primary_button      = "Plus de réalisations"
    primary_button_url  = "projects"

  [params.about]
    enable              = true
    title               = "A propos"
    subtitle            = "About"
    image_small         = "/images/vivieng-about-small.jpg"
    image_big           = "/images/vivieng-about-big.jpg"
    alt                 = "VivienG"
    p_tag_1             = "Je m’appelle Grenier Vivien et je suis développeur web freelance."
    p_tag_2             = "Autonome et motivé, je suis capable de créer des applications web et de donner vie à des maquettes. Souvent curieux, je m'intéresse à de nombreux sujets tels que le design, l'expérience utilisateur et l'optimisation."
    p_tag_3             = "Je suis toujours enthousiaste à l'idée de démarrer un nouveau projet !"

  [params.p404]
    enable              = true
    title               = "404"
    image               = "/images/Galaxy-Quest-Screen-Shots-tony-shalhoub.jpg"
    h2                  = "Un terrible incident c'est produit !"
    p_tag_1             = "Suite à une collision avec l'astéroïde B404c, une brèche dans la sphère de béryllium qui alimente le serveur du site cause des problèmes."
    p_tag_2             = "Bien naturellement j'ai mis mes meilleurs techniciens sur le coup."  

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        description = "Design et intégration par VivienG. © 2021-2023"